version: '3.4'

services:

  consul:
    image: consul:latest
    ports:
      - "8500:8500/tcp"
      - "8300:8300/tcp"
    hostname: consul
    container_name: consul

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis

  api.gateway:
    ports: 
      - "8080:80"
      - "8081:443"
    expose:
      - "8080"
      - "8081"
    depends_on:
      - consul
      - redis
    build:
      context: ./auth-demo-gateway/
      dockerfile: Dockerfile.compose
    links:
      - "consul"
      - "redis"
    hostname: apigateway
    container_name: apigateway

  userapi:
    ports: 
      - "8082:80"
      - "8083:443"
    expose:
      - "8082"
      - "8083"
    depends_on:
      - consul
      - api.gateway
    build:
      context: ./auth-demo-gateway-api/
      dockerfile: Dockerfile.compose
    links:
      - "consul"
      - "api.gateway"
    hostname: userapi
    container_name: api

  usercolourapi:
    ports: 
      - "8084:80"
      - "8085:443"
    expose:
      - "8084"
      - "8085"
    depends_on:
      - consul
      - api.gateway
    build:
      context: ./auth-demo-gateway-api-2/
      dockerfile: Dockerfile.compose
    links:
      - "consul"
      - "api.gateway"
    hostname: usercolourapi
    container_name: api-2

  angularspa:
    ports:
      - "8090:80"
      - "8091:443"
    expose:
      - "8090"
      - "8091"
    depends_on:
      - consul
      - api.gateway
    build:
      context: ./auth-demo-gateway-angularspa/
      dockerfile: Dockerfile.compose
    links:
      - "consul"
      - "api.gateway"
    hostname: angularspa
    container_name: angularspa
  