FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y build-essential nodejs && \
    apt-get install npm
WORKDIR /src
COPY ["./auth-demo-gateway-angularspa.csproj", ""]
RUN dotnet restore "auth-demo-gateway-angularspa.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "auth-demo-gateway-angularspa.csproj" -c Debug -o /app

FROM build AS publish
RUN dotnet publish "auth-demo-gateway-angularspa.csproj" -c Debug -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "auth-demo-gateway-angularspa.dll"]